Fashison_eCommerce/Models/MainType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fashison_eCommerce.Models
{
    public class MainType
    {
        public int ID { get; set; }
        public string Name { get; set; }

    }
}

Fashison_eCommerce/Areas/Admin/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fashison_eCommerce.Models;

namespace Fashison_eCommerce.Areas.Admin.Controllers
{
    public class ProductsController : Controller
    {
        private DB_A6A231_DAQLTMDTEntities db = new DB_A6A231_DAQLTMDTEntities();

        // GET: Admin/Products
        public ActionResult Index()
        {
            if (Session["Email"] != null)
            {
                ViewBag.type = db.Main_Type.ToList();
                var products = db.Products.Include(p => p.Brand).Include(p => p.Store).Include(p => p.Product_Type);
                ViewBag.product = products.ToList();
                ViewBag.shop = db.Stores.ToList();
                ViewBag.brand = db.Brands.ToList();
                return View();
            }
            else
            {
                return Redirect("/Admin/Home/Login");
            }
            
        }


        // GET: Admin/Products/Create
        public ActionResult Create()
        {
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName");
            ViewBag.Store_ID = new SelectList(db.Stores, "Store_ID", "Address");
            ViewBag.TypeID = new SelectList(db.Product_Type, "TypeID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection form)
        {
            int id = Convert.ToInt32(form["Id"]);
            string name = form["name"].ToString();
            int price = Convert.ToInt32(form["Price"]);
            int amount = Convert.ToInt32(form["Amount"]);
            int type = Convert.ToInt32(form["Type"]);
            int store = Convert.ToInt32(form["Store"]);
            int brand = Convert.ToInt32(form["Brand"]);
            string des = form["Description"].ToString();
            Product product = new Product() { Product_ID=id, Name = name, Price = price, Amount = amount, TypeID = type, Store_ID = store, BrandID = brand, Decription = des };
            db.Products.Add(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Admin/Products/Edit/5
        public ActionResult Edit(int? id)
        {
            Product product = db.Products.Find(id);
            ViewBag.product = product;
            ViewBag.TypeID = db.Main_Type.Find(product.Product_Type.Main_Type.ID);
            ViewBag.BrandID = db.Brands.Find(product.BrandID);
            ViewBag.StoreID = db.Stores.Find(product.Store_ID);
            ViewBag.brand = db.Brands;
            ViewBag.store = db.Stores;
            ViewBag.type = db.Main_Type;
            return PartialView("_ProductEdit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(FormCollection form)
        {
            int id = Convert.ToInt32(form["Id"]);
            string name = form["name"].ToString();
            int price = Convert.ToInt32(form["Price"]);
            int amount = Convert.ToInt32(form["Amount"]);
            int type = Convert.ToInt32(form["Type"]);
            int store = Convert.ToInt32(form["Store"]);
            int brand = Convert.ToInt32(form["Brand"]);
            string des = form["Description"].ToString();
            Product product = new Product() { Product_ID = id, Name = name, Price = price, Amount = amount, TypeID = type, Store_ID = store, Pictures = null, BrandID = brand, Decription = des, status=0 };
            db.Entry(product).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        // POST: Admin/Products/Delete/5

        public ActionResult Delete(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Confirm(int id)
        {
            db.sp_ConfirmProduct_Admin(id);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fashison_eCommerce/Areas/Buyer/Controllers/ProductDetailController.cs
using Fashison_eCommerce.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Fashison_eCommerce.Areas.Buyer.Controllers
{
    public class ProductDetailController : Controller
    {
        DB_A6A231_DAQLTMDTEntities db = new DB_A6A231_DAQLTMDTEntities();

        // GET: Buyer/ProductDetail
        public ActionResult Index()
        {
            return View();
        }

        // GET: Buyer/ProductDetail/Details/5
        public ActionResult Details(int id)
        {
            if (id == default)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            // chi tiet san pham
            ProductClient CC = new ProductClient();
            ViewBag.detail = CC.find(id);

            // thong tin nhan hieu san pham
            int brandID = Convert.ToInt32(CC.find(id).Select(x => x.BrandID).FirstOrDefault());
            ViewBag.brand = db.Brands.Where(x => x.BrandID == brandID).FirstOrDefault();

            // Lay thong tin cua hang
            int storeID = Convert.ToInt32(CC.find(id).Select(x => x.Store_ID).FirstOrDefault());
            Getstore(storeID);

            GetSubtype();

            if (ViewBag.detail == null)
            {
                return HttpNotFound();
            }
            return View();
        }

        public ActionResult GetSubtype()
        {
            ViewBag.subType = db.Product_Type.ToList();
            return View();
        }

        public ActionResult Getstore(int id)
        {
            ViewBag.store = db.Stores.Where(x => x.Store_ID == id).FirstOrDefault();
            return View();
        }

        public PartialViewResult ProductType()
        {
            MainTypeClient MC = new MainTypeClient();
            ViewBag.listType = MC.findAll();
            GetSubtype();
            return PartialView();
        }

        public ActionResult RelatedProduct(int typeid)
        {
            ProductClient CC = new ProductClient();
            //can san pham cung loai
            ViewBag.ProductsByType = CC.findbyType(typeid).OrderByDescending(x => x.Name);
            return View();
        }

        public PartialViewResult MainType()
        {
            MainTypeClient MC = new MainTypeClient();
            ViewBag.mainType = MC.findAll();
            return PartialView();
        }

        public PartialViewResult ProductOfStore(int storeid)
        {
            ProductClient PC = new ProductClient();
            ViewBag.prodOfStore = PC.findbyStore(storeid);
            return PartialView();
        }

        public ActionResult SearchProduct(int id)
        {

            return View();
        }
    }
}

Fashison_eCommerce/Areas/Seller/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.OleDb;
using System.Data.SqlClient;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

using Fashison_eCommerce.Models;
using Fashison_eCommerce.ViewModel;

using PagedList;
using Spire.Xls;


namespace Fashison_eCommerce.Areas.Seller.Controllers
{
    public class ProductsController : Controller
    {
        private DB_A6A231_DAQLTMDTEntities db = new DB_A6A231_DAQLTMDTEntities();

   
        // GET: Seller/Products
        public ActionResult Index()
        {

            ViewBag.MaintypeID = new SelectList(db.Main_Type, "ID", "Name");
            ViewBag.TypeID = new SelectList(db.Product_Type, "TypeID", "Name");



            ProductsClient CC = new ProductsClient();
            int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));
            ViewBag.listProducts = CC.findAll(Storeid);



            return View();


        }
        //public PartialViewResult Getpaging(int? page)
        //{

        //    ProductClient CC = new ProductClient();
        //    int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));

        //    int pageNumber = (page ?? 1);
        //    ViewBag.listProducts = CC.findAll(Storeid).ToPagedList(pageNumber, pageSize);
        //    //return View("Index");
        //    return PartialView("~/Areas/Seller/Views/Products/Search.cshtml");
        //}
        //public ActionResult Paginate(int pageNumber)
        //{
        //    ProductsClient CC = new ProductsClient();
        //    int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));
        //    ViewBag.listProducts = CC.findAll(Storeid).ToPagedList(pageNumber, PageSize);
        //    return PartialView("~/Areas/Seller/Views/Products/Search.cshtml");
        //}
        public ActionResult Search(string Name, int TypeID, int MinAmount, int MaxAmount)
        {



            ProductsClient CC = new ProductsClient();
            int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));
            Find filter = new Find();
            filter.StoreID = Storeid;
            filter.Name = Name;
            filter.TypeID = TypeID;
            filter.QualityMin = MinAmount;
            filter.QualityMax = MaxAmount;



            ViewBag.listProducts = CC.filter(filter);

            return PartialView("~/Areas/Seller/Views/Products/Search.cshtml");


            //}

        }
        public JsonResult GetTypeList(int MaintypeID)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Product_Type> ListType = db.Product_Type.Where(x => x.MaintypeID == MaintypeID).ToList();
            return Json(ListType, JsonRequestBehavior.AllowGet);
        }



        // GET: Seller/Products/Create
        public ActionResult Create()
        {

            ViewBag.TypeID = new SelectList(db.Product_Type, "TypeID", "Name");


            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName");
            return View();
        }

        // POST: Seller/Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ProductViewModel cvm, HttpPostedFileBase file)
        {

            //HttpPostedFileBase file = Request.Files[0];
            if (ModelState.IsValid)
            {

                if (file != null)
                {
                    string ImageName = Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Product_Images/" + ImageName);

                    // save image in folder
                    file.SaveAs(physicalPath);
                    cvm.product.Pictures = ImageName;
                }
                ProductsClient CC = new ProductsClient();
                int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));
                cvm.product.Store_ID = Storeid;
                CC.Create(cvm.product);

            }

            return RedirectToAction("Index");







        }

        // GET: Seller/Products/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            ProductsClient CC = new ProductsClient();
            ProductViewModel CVM = new ProductViewModel();
            CVM.product = CC.find(id);
            ViewBag.TypeID = new SelectList(db.Product_Type, "TypeID", "Name", CVM.product.TypeID);
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "BrandName", CVM.product.BrandID);
            return View("Edit", CVM);
        }

        // POST: Seller/Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(ProductViewModel CVM, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {

                ProductsClient CC = new ProductsClient();
                if (file == null)
                {
                    CVM.product.Pictures = CC.find(CVM.product.Product_ID).Pictures;
                }
                else
                {
                    string ImageName = Path.GetFileName(file.FileName);
                    string physicalPath = Server.MapPath("~/Product_Images/" + ImageName);

                    // save image in folder
                    file.SaveAs(physicalPath);
                    CVM.product.Pictures = ImageName;
                }
                int Storeid = CC.Storeid(Convert.ToInt32(Session["userID"]));
                CVM.product.Store_ID = Storeid;
                CC.Edit(CVM.product);
            }
            return RedirectToAction("Index");
        }


        // GET: Seller/Products/Delete/5
        public ActionResult Delete(int id)
        {
            ProductsClient CC = new ProductsClient();
            CC.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public void ImportFromExcel(HttpPostedFileBase postedFile)
        {
         
            if (ModelState.IsValid)
            {
                if (postedFile == null || postedFile.ContentLength > (1024 * 1024 * 50))  // 50MB limit  
                {
                    ModelState.AddModelError("postedFile", "Your file is to large. Maximum size allowed is 50MB !");
                }

                else
                {
                    string filePath = string.Empty;
                    string path = Server.MapPath("~/Uploads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }

                    filePath = path + Path.GetFileName(postedFile.FileName);
                    string extension = Path.GetExtension(postedFile.FileName);
                    postedFile.SaveAs(filePath);

                    string conString = string.Empty;
                    switch (extension)
                    {
                        case ".xls": //For Excel 97-03.  
                            conString = ConfigurationManager.ConnectionStrings["Excel03ConString"].ConnectionString;
                            break;
                        case ".xlsx": //For Excel 07 and above.  
                            conString = ConfigurationManager.ConnectionStrings["Excel07ConString"].ConnectionString;
                            break;
                    }

                    try
                    {
                        DataTable dt = new DataTable();
                        conString = string.Format(conString, filePath);

                        using (OleDbConnection connExcel = new OleDbConnection(conString))
                        {
                            using (OleDbCommand cmdExcel = new OleDbCommand())
                            {
                                using (OleDbDataAdapter odaExcel = new OleDbDataAdapter())
                                {
                                    cmdExcel.Connection = connExcel;

                                    //Get the name of First Sheet.  
                                    connExcel.Open();
                                    DataTable dtExcelSchema;
                                    dtExcelSchema = connExcel.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                                    string sheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                                    connExcel.Close();
                                    

                                    //Read Data from First Sheet.  
                                    connExcel.Open();
                                    cmdExcel.CommandText = "SELECT * From [" + sheetName + "]";
                                    odaExcel.SelectCommand = cmdExcel;
                                    odaExcel.Fill(dt);
                                    connExcel.Close();
                                }
                            }
                        }

                        conString = ConfigurationManager.ConnectionStrings["DB_A6A231_DAQLTMDTEntities_SQL"].ConnectionString;
                        using (SqlConnection con = new SqlConnection(conString))
                        {
                            using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                            {
                                //Set the database table name.  
                                sqlBulkCopy.DestinationTableName = "Product";
                                
                                con.Open();
                                sqlBulkCopy.ColumnMappings.Add("Name", "Name");

Fashison_eCommerce/Areas/Buyer/Views/ProductDetail/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var prod = ViewBag.detail[0];
}
@{
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                <div class="well well-small">
                    <a id="myCart" href="/UserCart">
                        <img src="~/Styles_css/User_styles/themes/images/ico-cart.png" alt="cart">
                        <div class="cart_info">
                            @{Html.RenderAction("CartInfo", "usercart");}
                        </div>

                    </a>
                </div>
                <ul id="sideManu" class="nav nav-tabs nav-stacked">
                    @{ Html.RenderAction("ProductType", "ProductDetail");}
                </ul>
            </div>
            <!-- Sidebar end=============================================== -->
            <div class="span9">
                <ul class="breadcrumb">
                    <li><a href="/">Home</a> <span class="divider">/</span></li>
                    <li><a href="">Products</a> <span class="divider">/</span></li>
                    <li class="active">product Details</li>
                </ul>
                <div class="row">

                    <div id="gallery" class="span3">
                        <a href="~/Product_Images/@prod.Pictures" title="@prod.Name" style="width: 220px">
                            <img src="~/Product_Images/@prod.Pictures" alt="@prod.Name" style="weight:100%;"/>
                        </a>
                        <div id="differentview" class="moreOptopm carousel slide"></div>

                        <div class="btn-toolbar">
                            <div class="btn-group">
                                <span class="btn"><i class="icon-envelope"></i></span>
                                <span class="btn"><i class="icon-print"></i></span>
                                <span class="btn"><i class="icon-zoom-in"></i></span>
                                <span class="btn"><i class="icon-star"></i></span>
                                <span class="btn"><i class=" icon-thumbs-up"></i></span>
                                <span class="btn"><i class="icon-thumbs-down"></i></span>
                            </div>
                        </div>
                    </div>
                    <div class="span6">
                        <h3> @prod.Name  </h3>
                        <small>@prod.Decription</small>
                        <hr class="soft" />
                        <form class="form-horizontal qtyFrm">
                            <div class="control-group">
                                <label class="control-label"><span style="color: orange; font-size: x-large; font-weight: bold;">@String.Format(info, "{0:C0}", prod.Price)</span></label>
                                <div class="controls">
                                    @*<input type="number" class="span1" placeholder="Qty." />*@
                                    <button type="submit" class="btn AddToCart btn-large btn-primary pull-right" data-product_id="@prod.Product_ID"> Add to cart <i class=" icon-shopping-cart"></i></button>
                                </div>
                            </div>
                        </form>

                        <hr class="soft" />
                        <h4>@prod.Amount items in stock</h4>

                    </div>
                    <hr class="soft">
                    <div class="span9" style="background-color: antiquewhite ">
                        <div class="row">
                            <div class="span2" >
                                <div class="brand" href="/Buyer/Shop/Index?id=@ViewBag.store.Store_ID" style="padding: 20px 0px 30px 30px; width:150px">
                                    <img src="~/Product_Images/@ViewBag.store.Pictures" style="width: 100px; height: 100px;" alt="Esshop">  
                                </div>
                            </div>
                            <div class="span3" style="margin-top: 40px">
                                <a href="/Buyer/Shop/Index?id=@ViewBag.store.Store_ID"> @ViewBag.store.ShopName </a>
                                <h5> @ViewBag.store.Address</h5>
                            </div>
                        </div>
                    </div>
                    <hr class="soft">
                    <div class="span9">
                        <ul id="productDetail" class="nav nav-tabs">
                            <li class="active"><a href="#home" data-toggle="tab">Product Details</a></li>
                            <li><a href="#profile" data-toggle="tab">Related Products</a></li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div class="tab-pane fade active in" id="home">
                                <h4>Product Information</h4>
                                <table class="table table-bordered">
                                    <tbody>
                                        <tr class="techSpecRow"><th colspan="2">Product Details</th></tr>
                                        <tr class="techSpecRow"><td class="techSpecTD1">Brand: </td><td class="techSpecTD2"> @ViewBag.brand.BrandName </td></tr>
                                        <tr class="techSpecRow"><td class="techSpecTD1">Shop: </td><td class="techSpecTD2"> @ViewBag.store.ShopName@*<a class="btn btn-small pull-right" onclick="BtnClick" >More Info</a>*@</td></tr>

                                    </tbody>

                                </table>
                                <hr class="soft">
                                <h4>Product of shop</h4>
                                <div class="loader" data-action="/Buyer/ProductDetail/ProductOfStore/@prod.Store_ID">
                                    @{ Html.RenderAction("ProductOfStore", "ProductDetail", new { storeid = prod.Store_ID });}
                                </div>
                            </div>
                            <div class="tab-pane fade" id="profile">
                                <div id="myTab" class="pull-right">
                                    <a href="#listView" data-toggle="tab"><span class="btn btn-large"><i class="icon-list"></i></span></a>
                                    <a href="#blockView" data-toggle="tab"><span class="btn btn-large btn-primary"><i class="icon-th-large"></i></span></a>
                                </div>
                                <br class="clr" />
                                <hr class="soft" />
                                <!-- related product ========================================= -->

                                @{ Html.RenderAction("RelatedProduct", "ProductDetail", new { typeid = prod.TypeID });}

                            </div>
                            <!-- ========================================= -->
                            <br class="clr">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- MainBody End ============================= -->
<script language="javascript">
    // gan event cho cac button add to cart
    var user = {
        init: function () {
            console.log("init");
            user.registerEvents();
        },
        registerEvents: function () {
            $('.AddToCart').off('click').on('click', function (e) {
                console.log("click");
                e.preventDefault();
                var id = $(this).data('product_id');
                console.log(id);
                // them san pham vao gio hang
                $.ajax({
                    url: "/Buyer/Cart_Item/AddToCart",
                    type: 'POST',
                    data: { ProductID: id },
                    success: function (msg) {
                        // load lai so san pham co trong gio hang
                        $.ajax({
                            url: "/Buyer/UserCart/CartInfo",
                            success: function (result) {
                                $(".cart_info").html(result);
                                alert('Add to cart successfully!');
                            }
                        });
                    }
                });
            });
        }
    }
    user.init();

</script>

Fashison_eCommerce/Areas/Buyer/Views/ProductDetail/MainType.cshtml
<select class="srchTxt" id="mainType">
    <option value="0">All</option>
    @foreach(var maintype in ViewBag.mainType)
    {
        <option value="@maintype.ID">@maintype.Name</option>
    }
</select>

Fashison_eCommerce/Areas/Buyer/Views/ProductDetail/ProductOfStore.cshtml
@{
    var info = System.Globalization.CultureInfo.GetCultureInfo("vi-VN"); }
<div class="tab-content">
    <ul class="thumbnails">
        @foreach (var prod in ViewBag.prodOfStore)
        {
            <li class="span3">
                <div class="thumbnail">
                    <a href="/Buyer/ProductDetail/Details?id=@prod.Product_ID"><img style="height: 215px; width: 215px" src="~/Product_Images/@prod.Pictures" alt="" /></a>
                    <div class="caption">
                        <h5>@prod.Name</h5>
                        <h4 style="text-align:center">
                            <a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a>
                            <a class="btn AddToCart" href="#" data-product_id="@prod.Product_ID">Add to <i class="icon-shopping-cart"></i></a>
                            <a class="btn btn-primary" href="#">@String.Format(info, "{0:C0}", prod.Price)</a>
                        </h4>
                    </div>
                </div>
            </li>
        }
    </ul>
    <hr class="soft" />
</div>

Fashison_eCommerce/Areas/Buyer/Views/ProductDetail/ProductType.cshtml
@{
    ViewBag.Title = "ProductType";
}
<ul id="sideManu" class="nav nav-tabs nav-stacked ">
    @foreach (var type in ViewBag.listType)
    {
        <li class="subMenu open">
            <a> @type.Name</a>

            <ul>

                @foreach (var sub in ViewBag.subType)
                {
                    if (sub.MaintypeID == type.ID)
                    {
                        @*<li><a class="active" href="products.html"><i class="icon-chevron-right"></i>Cameras (100) </a></li>*@
                        <li><a href="/Buyer/ProductbyType/Index?typeid=@sub.TypeID"><i class="icon-chevron-right"></i>@sub.Name</a></li>

                    }
                }
            </ul>
        </li>
    }
    </ul>

Fashison_eCommerce/Areas/Buyer/Views/ProductDetail/RelatedProduct.cshtml
@{
    Layout = null;
}


<div class="tab-content">
    <div class="tab-pane" id="listView">
        @foreach (var prod1 in ViewBag.ProductsByType)
        {
            <div class="row">
                <div class="span2">
                    <img src="~/Product_Images/@prod1.Pictures" alt="" style="width: 180px; height: 195px" />
                </div>
                <div class="span4">
                    <hr class="soft" />
                    <h4> @prod1.Name </h4>
                    <h5>
                        @prod1.Decription
                    </h5>
                    <a class="btn btn-small pull-right" href="/Buyer/ProductDetail/Details?id=@prod1.Product_ID">View Details</a>
                    <br class="clr" />
                </div>
                <div class="span3 alignR">
                    <form class="form-horizontal qtyFrm">
                        <h3>@prod1.Price</h3>
                        <label class="checkbox">
                        </label><br />
                        <div class="btn-group">
                            <a href="product_details.html" class="btn btn-large btn-primary"> Add to <i class=" icon-shopping-cart"></i></a>
                            <a href="product_details.html" class="btn btn-large"><i class="icon-zoom-in"></i></a>
                        </div>
                    </form>
                </div>
            </div>
            <hr class="soft" />
        }

    </div>
    <div class="tab-pane active" id="blockView">
        <ul class="thumbnails">
            @foreach (var prod in ViewBag.ProductsByType)
            {
                <li class="span3">
                    <div class="thumbnail">
                        <a href="/Buyer/ProductDetail/Details?id=@prod.Product_ID"><img src="~/Product_Images/@prod.Pictures" alt="" style="width: 190px; height: 210px" /></a>
                        <div class="caption">
                            <h5>@prod.Name</h5>
                            <p>
                                @prod.Decription
                            </p>
                            <h4 style="text-align:center"><a class="btn" href="/Buyer/ProductDetail/Details?id=@prod.Product_ID"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">@prod.Price</a></h4>
                        </div>
                    </div>
                </li>
            }
        </ul>
        <hr class="soft" />
    </div>

</div>