Fashison_eCommerce/Models/Store.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fashison_eCommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Store()
        {
            this.Orders = new HashSet<Order>();
            this.Products = new HashSet<Product>();
        }
    
        public int Store_ID { get; set; }
        public string Address { get; set; }
        public Nullable<int> UserID { get; set; }
        public string ShopName { get; set; }
        public string Decription { get; set; }
        public string Pictures { get; set; }
        public string Coverpics { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        public virtual User User { get; set; }
    }
}

Fashison_eCommerce/Areas/Seller/Controllers/StoresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Fashison_eCommerce.Models;
using Fashison_eCommerce.ViewModel;

namespace Fashison_eCommerce.Areas.Seller.Controllers
{
    public class StoresController : Controller
    {
        private DB_A6A231_DAQLTMDTEntities db = new DB_A6A231_DAQLTMDTEntities();

        // GET: Seller/Stores
        public ActionResult Index()
        {
            StoreClient CC = new StoreClient();
            StoreViewModel CVM = new StoreViewModel();
            CVM.store = CC.find(Convert.ToInt32(Session["userID"]));
            return View(CVM);
        }





        // POST: Seller/Stores/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public ActionResult Edit(StoreViewModel CVM, HttpPostedFileBase file)
        {
            StoreClient CC = new StoreClient();
            StoreViewModel St = new StoreViewModel();
            St.store = CC.find(Convert.ToInt32(Session["userID"]));
            if (file == null)
            {
                CVM.store.Pictures = St.store.Pictures;
            }
            else
            {
                string ImageName = Path.GetFileName(file.FileName);
                string physicalPath = Server.MapPath("~/Product_Images/" + ImageName);

                // save image in folder
                file.SaveAs(physicalPath);
                CVM.store.Pictures = ImageName;
            }
            CVM.store.Store_ID = St.store.Store_ID;
            CVM.store.UserID = St.store.UserID;
            CC.Edit(CVM.store);

            return RedirectToAction("Index");
        }



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Fashison_eCommerce/Areas/Seller/Views/Stores/Index.cshtml
@model Fashison_eCommerce.ViewModel.StoreViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Seller/Views/Shared/_Layout.cshtml";
}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link href="~/Assets/Seller/css/Store.css" rel="stylesheet" />
<!------ Include the above in your HEAD tag ---------->

<div class="container emp-profile">
    @using (Html.BeginForm("Edit", "Stores", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="~/Product_Images/@Model.store.Pictures" class="img-responsive" id="targetImg" />
                    <div class="file btn btn-lg btn-primary">
                        Change Photo
                        <input type="file" name="file" id="file" accept="image/*" />
                    </div>
                    @*<div id="imgPreview" class="thumbnail">
                            <img src="~/images/@Model.store.Coverpics" class="img-responsive" id="targetImg" />

                        </div>*@
                </div>
            </div>
            <div class="col-md-8">
                <div class="form-group">
                    <label class="control-label">Tên Shop</label>
                    @Html.EditorFor(model => model.store.ShopName, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    <label class="control-label">Địa chỉ</label>
                    @Html.EditorFor(model => model.store.Address, new { htmlAttributes = new { @class = "form-control" } })
                </div>
                <div class="form-group">
                    <label class="control-label">Mô tả Shop</label>
                    @Html.TextAreaFor(model => model.store.Decription, new { @cols = "100", @rows = "8", @style = "width:100%;" })
                </div>
                <input type="submit" class="profile-edit-btn" name="btnAddMore" id="save" value="Lưu" />
            </div>


        </div>
    }


</div>
<script>
    $(document).ready(function () {
        $("#save").on("click", function () {
            alert('Lưu thành công');
        });

    });
</script>